// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(coinswapFFI)
import coinswapFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_coinswap_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_coinswap_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCoinswapFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol AddressProtocol: AnyObject, Sendable {
    
}
open class Address: AddressProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_coinswap_ffi_fn_clone_address(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_coinswap_ffi_fn_free_address(pointer, $0) }
    }

    

    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAddress: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Address

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Address {
        return Address(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Address) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Address {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Address, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddress_lift(_ pointer: UnsafeMutableRawPointer) throws -> Address {
    return try FfiConverterTypeAddress.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddress_lower(_ value: Address) -> UnsafeMutableRawPointer {
    return FfiConverterTypeAddress.lower(value)
}






public protocol AmountProtocol: AnyObject, Sendable {
    
}
open class Amount: AmountProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_coinswap_ffi_fn_clone_amount(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_coinswap_ffi_fn_free_amount(pointer, $0) }
    }

    

    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAmount: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Amount

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Amount {
        return Amount(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Amount) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Amount {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Amount, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAmount_lift(_ pointer: UnsafeMutableRawPointer) throws -> Amount {
    return try FfiConverterTypeAmount.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAmount_lower(_ value: Amount) -> UnsafeMutableRawPointer {
    return FfiConverterTypeAmount.lower(value)
}






public protocol OutPointProtocol: AnyObject, Sendable {
    
}
open class OutPoint: OutPointProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_coinswap_ffi_fn_clone_outpoint(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_coinswap_ffi_fn_free_outpoint(pointer, $0) }
    }

    

    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOutPoint: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = OutPoint

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> OutPoint {
        return OutPoint(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: OutPoint) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OutPoint {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: OutPoint, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOutPoint_lift(_ pointer: UnsafeMutableRawPointer) throws -> OutPoint {
    return try FfiConverterTypeOutPoint.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOutPoint_lower(_ value: OutPoint) -> UnsafeMutableRawPointer {
    return FfiConverterTypeOutPoint.lower(value)
}






public protocol ScriptBufProtocol: AnyObject, Sendable {
    
}
open class ScriptBuf: ScriptBufProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_coinswap_ffi_fn_clone_scriptbuf(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_coinswap_ffi_fn_free_scriptbuf(pointer, $0) }
    }

    

    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScriptBuf: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ScriptBuf

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ScriptBuf {
        return ScriptBuf(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ScriptBuf) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScriptBuf {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ScriptBuf, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScriptBuf_lift(_ pointer: UnsafeMutableRawPointer) throws -> ScriptBuf {
    return try FfiConverterTypeScriptBuf.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScriptBuf_lower(_ value: ScriptBuf) -> UnsafeMutableRawPointer {
    return FfiConverterTypeScriptBuf.lower(value)
}






public protocol TakerProtocol: AnyObject, Sendable {
    
    /**
     * Display detailed information about a specific maker offer
     */
    func displayOffer(makerOffer: MakerOffer) throws  -> String
    
    func fetchAllMakers() throws  -> [String]
    
    func fetchGoodMakers() throws  -> [String]
    
    /**
     * Get basic information about all good makers (limited due to private fields)
     */
    func getAllGoodMakers() throws  -> [String]
    
    /**
     * Get wallet balances
     */
    func getWalletBalances() throws  -> Balances
    
    func getWalletName() throws  -> String
    
    /**
     * Recover from a failed swap
     */
    func recoverFromSwap() throws 
    
    func sendCoinswap(swapParams: SwapParams) throws 
    
    /**
     * Sync the offerbook with available makers
     */
    func syncOfferbook() throws 
    
    func syncWallet() throws 
    
}
open class Taker: TakerProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_coinswap_ffi_fn_clone_taker(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_coinswap_ffi_fn_free_taker(pointer, $0) }
    }

    
public static func `init`(dataDir: String?, walletFileName: String?, rpcConfig: RpcConfig?, behavior: TakerBehavior?, controlPort: UInt16?, torAuthPassword: String?)throws  -> Taker  {
    return try  FfiConverterTypeTaker_lift(try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_constructor_taker_init(
        FfiConverterOptionString.lower(dataDir),
        FfiConverterOptionString.lower(walletFileName),
        FfiConverterOptionTypeRPCConfig.lower(rpcConfig),
        FfiConverterOptionTypeTakerBehavior.lower(behavior),
        FfiConverterOptionUInt16.lower(controlPort),
        FfiConverterOptionString.lower(torAuthPassword),$0
    )
})
}
    

    
    /**
     * Display detailed information about a specific maker offer
     */
open func displayOffer(makerOffer: MakerOffer)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_method_taker_display_offer(self.uniffiClonePointer(),
        FfiConverterTypeMakerOffer_lower(makerOffer),$0
    )
})
}
    
open func fetchAllMakers()throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_method_taker_fetch_all_makers(self.uniffiClonePointer(),$0
    )
})
}
    
open func fetchGoodMakers()throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_method_taker_fetch_good_makers(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get basic information about all good makers (limited due to private fields)
     */
open func getAllGoodMakers()throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_method_taker_get_all_good_makers(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get wallet balances
     */
open func getWalletBalances()throws  -> Balances  {
    return try  FfiConverterTypeBalances_lift(try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_method_taker_get_wallet_balances(self.uniffiClonePointer(),$0
    )
})
}
    
open func getWalletName()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_method_taker_get_wallet_name(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Recover from a failed swap
     */
open func recoverFromSwap()throws   {try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_method_taker_recover_from_swap(self.uniffiClonePointer(),$0
    )
}
}
    
open func sendCoinswap(swapParams: SwapParams)throws   {try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_method_taker_send_coinswap(self.uniffiClonePointer(),
        FfiConverterTypeSwapParams_lower(swapParams),$0
    )
}
}
    
    /**
     * Sync the offerbook with available makers
     */
open func syncOfferbook()throws   {try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_method_taker_sync_offerbook(self.uniffiClonePointer(),$0
    )
}
}
    
open func syncWallet()throws   {try rustCallWithError(FfiConverterTypeTakerError_lift) {
    uniffi_coinswap_ffi_fn_method_taker_sync_wallet(self.uniffiClonePointer(),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaker: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Taker

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Taker {
        return Taker(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Taker) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Taker {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Taker, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaker_lift(_ pointer: UnsafeMutableRawPointer) throws -> Taker {
    return try FfiConverterTypeTaker.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaker_lower(_ value: Taker) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTaker.lower(value)
}






public protocol TxidProtocol: AnyObject, Sendable {
    
}
open class Txid: TxidProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_coinswap_ffi_fn_clone_txid(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_coinswap_ffi_fn_free_txid(pointer, $0) }
    }

    

    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTxid: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Txid

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Txid {
        return Txid(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Txid) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Txid {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Txid, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxid_lift(_ pointer: UnsafeMutableRawPointer) throws -> Txid {
    return try FfiConverterTypeTxid.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxid_lower(_ value: Txid) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTxid.lower(value)
}






public protocol WalletProtocol: AnyObject, Sendable {
    
    func backup(path: String) throws 
    
    func getBalances() throws  -> Balances
    
    /**
     * Get the wallet name
     */
    func getName()  -> String
    
    func getNextExternalAddress() throws  -> Address
    
    func getNextInternalAddresses(count: UInt32) throws  -> [Address]
    
    func listAllUtxos()  -> [UtxoWithSpendInfo]
    
    func lockUnspendableUtxos() throws 
    
    func syncAndSave() throws 
    
}
open class Wallet: WalletProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_coinswap_ffi_fn_clone_wallet(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_coinswap_ffi_fn_free_wallet(pointer, $0) }
    }

    
public static func `init`(path: String, rpcConfig: RpcConfig)throws  -> Wallet  {
    return try  FfiConverterTypeWallet_lift(try rustCallWithError(FfiConverterTypeWalletError_lift) {
    uniffi_coinswap_ffi_fn_constructor_wallet_init(
        FfiConverterString.lower(path),
        FfiConverterTypeRPCConfig_lower(rpcConfig),$0
    )
})
}
    

    
open func backup(path: String)throws   {try rustCallWithError(FfiConverterTypeWalletError_lift) {
    uniffi_coinswap_ffi_fn_method_wallet_backup(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
}
}
    
open func getBalances()throws  -> Balances  {
    return try  FfiConverterTypeBalances_lift(try rustCallWithError(FfiConverterTypeWalletError_lift) {
    uniffi_coinswap_ffi_fn_method_wallet_get_balances(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get the wallet name
     */
open func getName() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_coinswap_ffi_fn_method_wallet_get_name(self.uniffiClonePointer(),$0
    )
})
}
    
open func getNextExternalAddress()throws  -> Address  {
    return try  FfiConverterTypeAddress_lift(try rustCallWithError(FfiConverterTypeWalletError_lift) {
    uniffi_coinswap_ffi_fn_method_wallet_get_next_external_address(self.uniffiClonePointer(),$0
    )
})
}
    
open func getNextInternalAddresses(count: UInt32)throws  -> [Address]  {
    return try  FfiConverterSequenceTypeAddress.lift(try rustCallWithError(FfiConverterTypeWalletError_lift) {
    uniffi_coinswap_ffi_fn_method_wallet_get_next_internal_addresses(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(count),$0
    )
})
}
    
open func listAllUtxos() -> [UtxoWithSpendInfo]  {
    return try!  FfiConverterSequenceTypeUTXOWithSpendInfo.lift(try! rustCall() {
    uniffi_coinswap_ffi_fn_method_wallet_list_all_utxos(self.uniffiClonePointer(),$0
    )
})
}
    
open func lockUnspendableUtxos()throws   {try rustCallWithError(FfiConverterTypeWalletError_lift) {
    uniffi_coinswap_ffi_fn_method_wallet_lock_unspendable_utxos(self.uniffiClonePointer(),$0
    )
}
}
    
open func syncAndSave()throws   {try rustCallWithError(FfiConverterTypeWalletError_lift) {
    uniffi_coinswap_ffi_fn_method_wallet_sync_and_save(self.uniffiClonePointer(),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWallet: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Wallet

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Wallet {
        return Wallet(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Wallet) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Wallet {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Wallet, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWallet_lift(_ pointer: UnsafeMutableRawPointer) throws -> Wallet {
    return try FfiConverterTypeWallet.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWallet_lower(_ value: Wallet) -> UnsafeMutableRawPointer {
    return FfiConverterTypeWallet.lower(value)
}




public struct Balances {
    public var regular: UInt64
    public var swap: UInt64
    public var contract: UInt64
    public var fidelity: UInt64
    public var spendable: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(regular: UInt64, swap: UInt64, contract: UInt64, fidelity: UInt64, spendable: UInt64) {
        self.regular = regular
        self.swap = swap
        self.contract = contract
        self.fidelity = fidelity
        self.spendable = spendable
    }
}

#if compiler(>=6)
extension Balances: Sendable {}
#endif


extension Balances: Equatable, Hashable {
    public static func ==(lhs: Balances, rhs: Balances) -> Bool {
        if lhs.regular != rhs.regular {
            return false
        }
        if lhs.swap != rhs.swap {
            return false
        }
        if lhs.contract != rhs.contract {
            return false
        }
        if lhs.fidelity != rhs.fidelity {
            return false
        }
        if lhs.spendable != rhs.spendable {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(regular)
        hasher.combine(swap)
        hasher.combine(contract)
        hasher.combine(fidelity)
        hasher.combine(spendable)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBalances: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Balances {
        return
            try Balances(
                regular: FfiConverterUInt64.read(from: &buf), 
                swap: FfiConverterUInt64.read(from: &buf), 
                contract: FfiConverterUInt64.read(from: &buf), 
                fidelity: FfiConverterUInt64.read(from: &buf), 
                spendable: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Balances, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.regular, into: &buf)
        FfiConverterUInt64.write(value.swap, into: &buf)
        FfiConverterUInt64.write(value.contract, into: &buf)
        FfiConverterUInt64.write(value.fidelity, into: &buf)
        FfiConverterUInt64.write(value.spendable, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBalances_lift(_ buf: RustBuffer) throws -> Balances {
    return try FfiConverterTypeBalances.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBalances_lower(_ value: Balances) -> RustBuffer {
    return FfiConverterTypeBalances.lower(value)
}


public struct ListUnspentResultEntry {
    public var txid: Txid
    public var vout: UInt32
    public var address: String?
    public var label: String?
    public var scriptPubKey: ScriptBuf
    public var amount: Amount
    public var confirmations: UInt32
    public var redeemScript: ScriptBuf?
    public var witnessScript: ScriptBuf?
    public var spendable: Bool
    public var solvable: Bool
    public var desc: String?
    public var safe: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(txid: Txid, vout: UInt32, address: String?, label: String?, scriptPubKey: ScriptBuf, amount: Amount, confirmations: UInt32, redeemScript: ScriptBuf?, witnessScript: ScriptBuf?, spendable: Bool, solvable: Bool, desc: String?, safe: Bool) {
        self.txid = txid
        self.vout = vout
        self.address = address
        self.label = label
        self.scriptPubKey = scriptPubKey
        self.amount = amount
        self.confirmations = confirmations
        self.redeemScript = redeemScript
        self.witnessScript = witnessScript
        self.spendable = spendable
        self.solvable = solvable
        self.desc = desc
        self.safe = safe
    }
}

#if compiler(>=6)
extension ListUnspentResultEntry: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeListUnspentResultEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ListUnspentResultEntry {
        return
            try ListUnspentResultEntry(
                txid: FfiConverterTypeTxid.read(from: &buf), 
                vout: FfiConverterUInt32.read(from: &buf), 
                address: FfiConverterOptionString.read(from: &buf), 
                label: FfiConverterOptionString.read(from: &buf), 
                scriptPubKey: FfiConverterTypeScriptBuf.read(from: &buf), 
                amount: FfiConverterTypeAmount.read(from: &buf), 
                confirmations: FfiConverterUInt32.read(from: &buf), 
                redeemScript: FfiConverterOptionTypeScriptBuf.read(from: &buf), 
                witnessScript: FfiConverterOptionTypeScriptBuf.read(from: &buf), 
                spendable: FfiConverterBool.read(from: &buf), 
                solvable: FfiConverterBool.read(from: &buf), 
                desc: FfiConverterOptionString.read(from: &buf), 
                safe: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ListUnspentResultEntry, into buf: inout [UInt8]) {
        FfiConverterTypeTxid.write(value.txid, into: &buf)
        FfiConverterUInt32.write(value.vout, into: &buf)
        FfiConverterOptionString.write(value.address, into: &buf)
        FfiConverterOptionString.write(value.label, into: &buf)
        FfiConverterTypeScriptBuf.write(value.scriptPubKey, into: &buf)
        FfiConverterTypeAmount.write(value.amount, into: &buf)
        FfiConverterUInt32.write(value.confirmations, into: &buf)
        FfiConverterOptionTypeScriptBuf.write(value.redeemScript, into: &buf)
        FfiConverterOptionTypeScriptBuf.write(value.witnessScript, into: &buf)
        FfiConverterBool.write(value.spendable, into: &buf)
        FfiConverterBool.write(value.solvable, into: &buf)
        FfiConverterOptionString.write(value.desc, into: &buf)
        FfiConverterBool.write(value.safe, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListUnspentResultEntry_lift(_ buf: RustBuffer) throws -> ListUnspentResultEntry {
    return try FfiConverterTypeListUnspentResultEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListUnspentResultEntry_lower(_ value: ListUnspentResultEntry) -> RustBuffer {
    return FfiConverterTypeListUnspentResultEntry.lower(value)
}


public struct MakerOffer {
    public var baseFee: UInt64
    public var amountRelativeFeePct: Double
    public var timeRelativeFeePct: Double
    public var requiredConfirms: UInt32
    public var minimumLocktime: UInt16
    public var maxSize: UInt64
    public var minSize: UInt64
    public var address: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(baseFee: UInt64, amountRelativeFeePct: Double, timeRelativeFeePct: Double, requiredConfirms: UInt32, minimumLocktime: UInt16, maxSize: UInt64, minSize: UInt64, address: String) {
        self.baseFee = baseFee
        self.amountRelativeFeePct = amountRelativeFeePct
        self.timeRelativeFeePct = timeRelativeFeePct
        self.requiredConfirms = requiredConfirms
        self.minimumLocktime = minimumLocktime
        self.maxSize = maxSize
        self.minSize = minSize
        self.address = address
    }
}

#if compiler(>=6)
extension MakerOffer: Sendable {}
#endif


extension MakerOffer: Equatable, Hashable {
    public static func ==(lhs: MakerOffer, rhs: MakerOffer) -> Bool {
        if lhs.baseFee != rhs.baseFee {
            return false
        }
        if lhs.amountRelativeFeePct != rhs.amountRelativeFeePct {
            return false
        }
        if lhs.timeRelativeFeePct != rhs.timeRelativeFeePct {
            return false
        }
        if lhs.requiredConfirms != rhs.requiredConfirms {
            return false
        }
        if lhs.minimumLocktime != rhs.minimumLocktime {
            return false
        }
        if lhs.maxSize != rhs.maxSize {
            return false
        }
        if lhs.minSize != rhs.minSize {
            return false
        }
        if lhs.address != rhs.address {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(baseFee)
        hasher.combine(amountRelativeFeePct)
        hasher.combine(timeRelativeFeePct)
        hasher.combine(requiredConfirms)
        hasher.combine(minimumLocktime)
        hasher.combine(maxSize)
        hasher.combine(minSize)
        hasher.combine(address)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMakerOffer: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MakerOffer {
        return
            try MakerOffer(
                baseFee: FfiConverterUInt64.read(from: &buf), 
                amountRelativeFeePct: FfiConverterDouble.read(from: &buf), 
                timeRelativeFeePct: FfiConverterDouble.read(from: &buf), 
                requiredConfirms: FfiConverterUInt32.read(from: &buf), 
                minimumLocktime: FfiConverterUInt16.read(from: &buf), 
                maxSize: FfiConverterUInt64.read(from: &buf), 
                minSize: FfiConverterUInt64.read(from: &buf), 
                address: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MakerOffer, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.baseFee, into: &buf)
        FfiConverterDouble.write(value.amountRelativeFeePct, into: &buf)
        FfiConverterDouble.write(value.timeRelativeFeePct, into: &buf)
        FfiConverterUInt32.write(value.requiredConfirms, into: &buf)
        FfiConverterUInt16.write(value.minimumLocktime, into: &buf)
        FfiConverterUInt64.write(value.maxSize, into: &buf)
        FfiConverterUInt64.write(value.minSize, into: &buf)
        FfiConverterString.write(value.address, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMakerOffer_lift(_ buf: RustBuffer) throws -> MakerOffer {
    return try FfiConverterTypeMakerOffer.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMakerOffer_lower(_ value: MakerOffer) -> RustBuffer {
    return FfiConverterTypeMakerOffer.lower(value)
}


public struct MakerStats {
    public var totalMakers: UInt32
    public var onlineMakers: UInt32
    public var avgBaseFee: UInt64
    public var avgAmountRelativeFeePct: Double
    public var avgTimeRelativeFeePct: Double
    public var totalLiquidity: UInt64
    public var avgMinSize: UInt64
    public var avgMaxSize: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(totalMakers: UInt32, onlineMakers: UInt32, avgBaseFee: UInt64, avgAmountRelativeFeePct: Double, avgTimeRelativeFeePct: Double, totalLiquidity: UInt64, avgMinSize: UInt64, avgMaxSize: UInt64) {
        self.totalMakers = totalMakers
        self.onlineMakers = onlineMakers
        self.avgBaseFee = avgBaseFee
        self.avgAmountRelativeFeePct = avgAmountRelativeFeePct
        self.avgTimeRelativeFeePct = avgTimeRelativeFeePct
        self.totalLiquidity = totalLiquidity
        self.avgMinSize = avgMinSize
        self.avgMaxSize = avgMaxSize
    }
}

#if compiler(>=6)
extension MakerStats: Sendable {}
#endif


extension MakerStats: Equatable, Hashable {
    public static func ==(lhs: MakerStats, rhs: MakerStats) -> Bool {
        if lhs.totalMakers != rhs.totalMakers {
            return false
        }
        if lhs.onlineMakers != rhs.onlineMakers {
            return false
        }
        if lhs.avgBaseFee != rhs.avgBaseFee {
            return false
        }
        if lhs.avgAmountRelativeFeePct != rhs.avgAmountRelativeFeePct {
            return false
        }
        if lhs.avgTimeRelativeFeePct != rhs.avgTimeRelativeFeePct {
            return false
        }
        if lhs.totalLiquidity != rhs.totalLiquidity {
            return false
        }
        if lhs.avgMinSize != rhs.avgMinSize {
            return false
        }
        if lhs.avgMaxSize != rhs.avgMaxSize {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(totalMakers)
        hasher.combine(onlineMakers)
        hasher.combine(avgBaseFee)
        hasher.combine(avgAmountRelativeFeePct)
        hasher.combine(avgTimeRelativeFeePct)
        hasher.combine(totalLiquidity)
        hasher.combine(avgMinSize)
        hasher.combine(avgMaxSize)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMakerStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MakerStats {
        return
            try MakerStats(
                totalMakers: FfiConverterUInt32.read(from: &buf), 
                onlineMakers: FfiConverterUInt32.read(from: &buf), 
                avgBaseFee: FfiConverterUInt64.read(from: &buf), 
                avgAmountRelativeFeePct: FfiConverterDouble.read(from: &buf), 
                avgTimeRelativeFeePct: FfiConverterDouble.read(from: &buf), 
                totalLiquidity: FfiConverterUInt64.read(from: &buf), 
                avgMinSize: FfiConverterUInt64.read(from: &buf), 
                avgMaxSize: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MakerStats, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.totalMakers, into: &buf)
        FfiConverterUInt32.write(value.onlineMakers, into: &buf)
        FfiConverterUInt64.write(value.avgBaseFee, into: &buf)
        FfiConverterDouble.write(value.avgAmountRelativeFeePct, into: &buf)
        FfiConverterDouble.write(value.avgTimeRelativeFeePct, into: &buf)
        FfiConverterUInt64.write(value.totalLiquidity, into: &buf)
        FfiConverterUInt64.write(value.avgMinSize, into: &buf)
        FfiConverterUInt64.write(value.avgMaxSize, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMakerStats_lift(_ buf: RustBuffer) throws -> MakerStats {
    return try FfiConverterTypeMakerStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMakerStats_lower(_ value: MakerStats) -> RustBuffer {
    return FfiConverterTypeMakerStats.lower(value)
}


public struct RpcConfig {
    public var url: String
    public var username: String
    public var password: String
    public var walletName: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(url: String, username: String, password: String, walletName: String) {
        self.url = url
        self.username = username
        self.password = password
        self.walletName = walletName
    }
}

#if compiler(>=6)
extension RpcConfig: Sendable {}
#endif


extension RpcConfig: Equatable, Hashable {
    public static func ==(lhs: RpcConfig, rhs: RpcConfig) -> Bool {
        if lhs.url != rhs.url {
            return false
        }
        if lhs.username != rhs.username {
            return false
        }
        if lhs.password != rhs.password {
            return false
        }
        if lhs.walletName != rhs.walletName {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(url)
        hasher.combine(username)
        hasher.combine(password)
        hasher.combine(walletName)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRPCConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RpcConfig {
        return
            try RpcConfig(
                url: FfiConverterString.read(from: &buf), 
                username: FfiConverterString.read(from: &buf), 
                password: FfiConverterString.read(from: &buf), 
                walletName: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RpcConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.username, into: &buf)
        FfiConverterString.write(value.password, into: &buf)
        FfiConverterString.write(value.walletName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRPCConfig_lift(_ buf: RustBuffer) throws -> RpcConfig {
    return try FfiConverterTypeRPCConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRPCConfig_lower(_ value: RpcConfig) -> RustBuffer {
    return FfiConverterTypeRPCConfig.lower(value)
}


public struct SwapParams {
    /**
     * Total Amount
     */
    public var sendAmount: UInt64
    /**
     * How many hops (number of makers)
     */
    public var makerCount: UInt32
    /**
     * User selected UTXOs (optional)
     */
    public var manuallySelectedOutpoints: [OutPoint]?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Total Amount
         */sendAmount: UInt64, 
        /**
         * How many hops (number of makers)
         */makerCount: UInt32, 
        /**
         * User selected UTXOs (optional)
         */manuallySelectedOutpoints: [OutPoint]?) {
        self.sendAmount = sendAmount
        self.makerCount = makerCount
        self.manuallySelectedOutpoints = manuallySelectedOutpoints
    }
}

#if compiler(>=6)
extension SwapParams: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSwapParams: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwapParams {
        return
            try SwapParams(
                sendAmount: FfiConverterUInt64.read(from: &buf), 
                makerCount: FfiConverterUInt32.read(from: &buf), 
                manuallySelectedOutpoints: FfiConverterOptionSequenceTypeOutPoint.read(from: &buf)
        )
    }

    public static func write(_ value: SwapParams, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.sendAmount, into: &buf)
        FfiConverterUInt32.write(value.makerCount, into: &buf)
        FfiConverterOptionSequenceTypeOutPoint.write(value.manuallySelectedOutpoints, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSwapParams_lift(_ buf: RustBuffer) throws -> SwapParams {
    return try FfiConverterTypeSwapParams.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSwapParams_lower(_ value: SwapParams) -> RustBuffer {
    return FfiConverterTypeSwapParams.lower(value)
}


public struct UtxoWithSpendInfo {
    public var utxo: ListUnspentResultEntry
    public var spendInfo: UtxoSpendInfo

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(utxo: ListUnspentResultEntry, spendInfo: UtxoSpendInfo) {
        self.utxo = utxo
        self.spendInfo = spendInfo
    }
}

#if compiler(>=6)
extension UtxoWithSpendInfo: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUTXOWithSpendInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UtxoWithSpendInfo {
        return
            try UtxoWithSpendInfo(
                utxo: FfiConverterTypeListUnspentResultEntry.read(from: &buf), 
                spendInfo: FfiConverterTypeUtxoSpendInfo.read(from: &buf)
        )
    }

    public static func write(_ value: UtxoWithSpendInfo, into buf: inout [UInt8]) {
        FfiConverterTypeListUnspentResultEntry.write(value.utxo, into: &buf)
        FfiConverterTypeUtxoSpendInfo.write(value.spendInfo, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUTXOWithSpendInfo_lift(_ buf: RustBuffer) throws -> UtxoWithSpendInfo {
    return try FfiConverterTypeUTXOWithSpendInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUTXOWithSpendInfo_lower(_ value: UtxoWithSpendInfo) -> RustBuffer {
    return FfiConverterTypeUTXOWithSpendInfo.lower(value)
}


public struct WalletBackup {
    public var fileName: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fileName: String) {
        self.fileName = fileName
    }
}

#if compiler(>=6)
extension WalletBackup: Sendable {}
#endif


extension WalletBackup: Equatable, Hashable {
    public static func ==(lhs: WalletBackup, rhs: WalletBackup) -> Bool {
        if lhs.fileName != rhs.fileName {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fileName)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalletBackup: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalletBackup {
        return
            try WalletBackup(
                fileName: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: WalletBackup, into buf: inout [UInt8]) {
        FfiConverterString.write(value.fileName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletBackup_lift(_ buf: RustBuffer) throws -> WalletBackup {
    return try FfiConverterTypeWalletBackup.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletBackup_lower(_ value: WalletBackup) -> RustBuffer {
    return FfiConverterTypeWalletBackup.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum TakerBehavior {
    
    case normal
    case dropConnectionAfterFullSetup
    case broadcastContractAfterFullSetup
}


#if compiler(>=6)
extension TakerBehavior: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTakerBehavior: FfiConverterRustBuffer {
    typealias SwiftType = TakerBehavior

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TakerBehavior {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .normal
        
        case 2: return .dropConnectionAfterFullSetup
        
        case 3: return .broadcastContractAfterFullSetup
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TakerBehavior, into buf: inout [UInt8]) {
        switch value {
        
        
        case .normal:
            writeInt(&buf, Int32(1))
        
        
        case .dropConnectionAfterFullSetup:
            writeInt(&buf, Int32(2))
        
        
        case .broadcastContractAfterFullSetup:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTakerBehavior_lift(_ buf: RustBuffer) throws -> TakerBehavior {
    return try FfiConverterTypeTakerBehavior.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTakerBehavior_lower(_ value: TakerBehavior) -> RustBuffer {
    return FfiConverterTypeTakerBehavior.lower(value)
}


extension TakerBehavior: Equatable, Hashable {}







public enum TakerError: Swift.Error {

    
    
    case Wallet(msg: String
    )
    case Protocol(msg: String
    )
    case Network(msg: String
    )
    case General(msg: String
    )
    case Io(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTakerError: FfiConverterRustBuffer {
    typealias SwiftType = TakerError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TakerError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Wallet(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Protocol(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Network(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .General(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Io(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TakerError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Wallet(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Protocol(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Network(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .General(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Io(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTakerError_lift(_ buf: RustBuffer) throws -> TakerError {
    return try FfiConverterTypeTakerError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTakerError_lower(_ value: TakerError) -> RustBuffer {
    return FfiConverterTypeTakerError.lower(value)
}


extension TakerError: Equatable, Hashable {}




extension TakerError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum UtxoSpendInfo {
    
    /**
     * Seed Coin
     */
    case seedCoin(path: String, inputValue: Amount
    )
    /**
     * Coins that we have received in a swap
     */
    case incomingSwapCoin(multisigRedeemscript: ScriptBuf
    )
    /**
     * Coins that we have sent in a swap
     */
    case outgoingSwapCoin(multisigRedeemscript: ScriptBuf
    )
    /**
     * Timelock Contract
     */
    case timelockContract(swapcoinMultisigRedeemscript: ScriptBuf, inputValue: Amount
    )
    /**
     * HashLockContract
     */
    case hashlockContract(swapcoinMultisigRedeemscript: ScriptBuf, inputValue: Amount
    )
    /**
     * Fidelity Bond Coin
     */
    case fidelityBondCoin(index: UInt32, inputValue: Amount
    )
    /**
     * Swept incoming swap coin
     */
    case sweptCoin(path: String, inputValue: Amount, originalMultisigRedeemscript: ScriptBuf
    )
}


#if compiler(>=6)
extension UtxoSpendInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUtxoSpendInfo: FfiConverterRustBuffer {
    typealias SwiftType = UtxoSpendInfo

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UtxoSpendInfo {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .seedCoin(path: try FfiConverterString.read(from: &buf), inputValue: try FfiConverterTypeAmount.read(from: &buf)
        )
        
        case 2: return .incomingSwapCoin(multisigRedeemscript: try FfiConverterTypeScriptBuf.read(from: &buf)
        )
        
        case 3: return .outgoingSwapCoin(multisigRedeemscript: try FfiConverterTypeScriptBuf.read(from: &buf)
        )
        
        case 4: return .timelockContract(swapcoinMultisigRedeemscript: try FfiConverterTypeScriptBuf.read(from: &buf), inputValue: try FfiConverterTypeAmount.read(from: &buf)
        )
        
        case 5: return .hashlockContract(swapcoinMultisigRedeemscript: try FfiConverterTypeScriptBuf.read(from: &buf), inputValue: try FfiConverterTypeAmount.read(from: &buf)
        )
        
        case 6: return .fidelityBondCoin(index: try FfiConverterUInt32.read(from: &buf), inputValue: try FfiConverterTypeAmount.read(from: &buf)
        )
        
        case 7: return .sweptCoin(path: try FfiConverterString.read(from: &buf), inputValue: try FfiConverterTypeAmount.read(from: &buf), originalMultisigRedeemscript: try FfiConverterTypeScriptBuf.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UtxoSpendInfo, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .seedCoin(path,inputValue):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(path, into: &buf)
            FfiConverterTypeAmount.write(inputValue, into: &buf)
            
        
        case let .incomingSwapCoin(multisigRedeemscript):
            writeInt(&buf, Int32(2))
            FfiConverterTypeScriptBuf.write(multisigRedeemscript, into: &buf)
            
        
        case let .outgoingSwapCoin(multisigRedeemscript):
            writeInt(&buf, Int32(3))
            FfiConverterTypeScriptBuf.write(multisigRedeemscript, into: &buf)
            
        
        case let .timelockContract(swapcoinMultisigRedeemscript,inputValue):
            writeInt(&buf, Int32(4))
            FfiConverterTypeScriptBuf.write(swapcoinMultisigRedeemscript, into: &buf)
            FfiConverterTypeAmount.write(inputValue, into: &buf)
            
        
        case let .hashlockContract(swapcoinMultisigRedeemscript,inputValue):
            writeInt(&buf, Int32(5))
            FfiConverterTypeScriptBuf.write(swapcoinMultisigRedeemscript, into: &buf)
            FfiConverterTypeAmount.write(inputValue, into: &buf)
            
        
        case let .fidelityBondCoin(index,inputValue):
            writeInt(&buf, Int32(6))
            FfiConverterUInt32.write(index, into: &buf)
            FfiConverterTypeAmount.write(inputValue, into: &buf)
            
        
        case let .sweptCoin(path,inputValue,originalMultisigRedeemscript):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(path, into: &buf)
            FfiConverterTypeAmount.write(inputValue, into: &buf)
            FfiConverterTypeScriptBuf.write(originalMultisigRedeemscript, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUtxoSpendInfo_lift(_ buf: RustBuffer) throws -> UtxoSpendInfo {
    return try FfiConverterTypeUtxoSpendInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUtxoSpendInfo_lower(_ value: UtxoSpendInfo) -> RustBuffer {
    return FfiConverterTypeUtxoSpendInfo.lower(value)
}







public enum WalletError: Swift.Error {

    
    
    case Io(msg: String
    )
    case Rpc(msg: String
    )
    case General(msg: String
    )
    case Json(msg: String
    )
    case Network(msg: String
    )
    case AddressParse(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalletError: FfiConverterRustBuffer {
    typealias SwiftType = WalletError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalletError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Io(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Rpc(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .General(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Json(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Network(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 6: return .AddressParse(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: WalletError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Io(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Rpc(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .General(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Json(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Network(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .AddressParse(msg):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletError_lift(_ buf: RustBuffer) throws -> WalletError {
    return try FfiConverterTypeWalletError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletError_lower(_ value: WalletError) -> RustBuffer {
    return FfiConverterTypeWalletError.lower(value)
}


extension WalletError: Equatable, Hashable {}




extension WalletError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeScriptBuf: FfiConverterRustBuffer {
    typealias SwiftType = ScriptBuf?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeScriptBuf.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeScriptBuf.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeRPCConfig: FfiConverterRustBuffer {
    typealias SwiftType = RpcConfig?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeRPCConfig.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeRPCConfig.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeTakerBehavior: FfiConverterRustBuffer {
    typealias SwiftType = TakerBehavior?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeTakerBehavior.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeTakerBehavior.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceTypeOutPoint: FfiConverterRustBuffer {
    typealias SwiftType = [OutPoint]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceTypeOutPoint.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceTypeOutPoint.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAddress: FfiConverterRustBuffer {
    typealias SwiftType = [Address]

    public static func write(_ value: [Address], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAddress.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Address] {
        let len: Int32 = try readInt(&buf)
        var seq = [Address]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAddress.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeOutPoint: FfiConverterRustBuffer {
    typealias SwiftType = [OutPoint]

    public static func write(_ value: [OutPoint], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeOutPoint.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [OutPoint] {
        let len: Int32 = try readInt(&buf)
        var seq = [OutPoint]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeOutPoint.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeUTXOWithSpendInfo: FfiConverterRustBuffer {
    typealias SwiftType = [UtxoWithSpendInfo]

    public static func write(_ value: [UtxoWithSpendInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeUTXOWithSpendInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UtxoWithSpendInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [UtxoWithSpendInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeUTXOWithSpendInfo.read(from: &buf))
        }
        return seq
    }
}
public func createDefaultRpcConfig() -> RpcConfig  {
    return try!  FfiConverterTypeRPCConfig_lift(try! rustCall() {
    uniffi_coinswap_ffi_fn_func_create_default_rpc_config($0
    )
})
}
public func createSwapParams(sendAmountSats: UInt64, makerCount: UInt32, outpoints: [OutPoint]) -> SwapParams  {
    return try!  FfiConverterTypeSwapParams_lift(try! rustCall() {
    uniffi_coinswap_ffi_fn_func_create_swap_params(
        FfiConverterUInt64.lower(sendAmountSats),
        FfiConverterUInt32.lower(makerCount),
        FfiConverterSequenceTypeOutPoint.lower(outpoints),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_coinswap_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_coinswap_ffi_checksum_func_create_default_rpc_config() != 9423) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_func_create_swap_params() != 64040) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_taker_display_offer() != 29310) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_taker_fetch_all_makers() != 10547) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_taker_fetch_good_makers() != 31706) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_taker_get_all_good_makers() != 35374) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_taker_get_wallet_balances() != 36988) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_taker_get_wallet_name() != 45636) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_taker_recover_from_swap() != 52494) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_taker_send_coinswap() != 5303) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_taker_sync_offerbook() != 43682) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_taker_sync_wallet() != 64892) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_wallet_backup() != 31141) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_wallet_get_balances() != 8214) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_wallet_get_name() != 46731) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_wallet_get_next_external_address() != 44927) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_wallet_get_next_internal_addresses() != 37843) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_wallet_list_all_utxos() != 25489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_wallet_lock_unspendable_utxos() != 58679) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_method_wallet_sync_and_save() != 32529) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_constructor_taker_init() != 56903) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_coinswap_ffi_checksum_constructor_wallet_init() != 14020) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCoinswapFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all