/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Taker {
  constructor(dataDir: string | undefined | null, walletFileName: string | undefined | null, rpcConfig: RpcConfig | undefined | null, controlPort: number | undefined | null, torAuthPassword: string | undefined | null, zmqAddr: string, password?: string | undefined | null)
  static setupLogging(dataDir: string | undefined | null, level: string): void
  static initNativeLogging(): void
  /** Fetch fee estimates from Mempool.space API with automatic fallback to Esplora */
  static fetchMempoolFees(): FeeRates
  doCoinswap(swapParams: SwapParams): SwapReport | null
  isOfferbookSyncing(): boolean
  runOfferSyncNow(): void
  getTransactions(count?: number | undefined | null, skip?: number | undefined | null): Array<ListTransactionResult>
  getNextInternalAddresses(count: number, addressType: AddressType): Array<Address>
  getNextExternalAddress(addressType: AddressType): Address
  getName(): string
  listAllUtxoSpendInfo(): Array<[ListUnspentResultEntry, UtxoSpendInfo]>
  backup(destinationPath: string, password?: string | undefined | null): void
  static restoreWalletGuiApp(dataDir: string | undefined | null, walletFileName: string | undefined | null, rpcConfig: RpcConfig, backupFile: string, password?: string | undefined | null): void
  lockUnspendableUtxos(): void
  sendToAddress(address: string, amount: number, feeRate?: number | undefined | null, manuallySelectedOutpoints?: Array<OutPoint> | undefined | null): Txid
  /** Get wallet balances */
  getBalances(): Balances
  syncAndSave(): void
  displayOffer(makerOffer: Offer): string
  /** Recover from a failed swap */
  recoverFromSwap(): void
  fetchAllMakers(): Array<string>
  fetchOffers(): OfferBook
  static isWalletEncrypted(walletPath: string): boolean
}

export declare class TaprootTaker {
  constructor(dataDir: string | undefined | null, walletFileName: string | undefined | null, rpcConfig: RpcConfig | undefined | null, controlPort: number | undefined | null, torAuthPassword: string | undefined | null, zmqAddr: string, password?: string | undefined | null)
  static setupLogging(dataDir: string | undefined | null, level: string): void
  static initNativeLogging(): void
  /** Fetch fee estimates from Mempool.space API with automatic fallback to Esplora */
  static fetchMempoolFees(): FeeRates
  /** Execute a Taproot coinswap */
  doCoinswap(swapParams: TaprootSwapParams): SwapReport | null
  runOfferSyncNow(): void
  isOfferbookSyncing(): boolean
  getTransactions(count?: number | undefined | null, skip?: number | undefined | null): Array<ListTransactionResult>
  getNextInternalAddresses(count: number, addressType: AddressType): Array<Address>
  getNextExternalAddress(addressType: AddressType): Address
  getName(): string
  listAllUtxoSpendInfo(): Array<[ListUnspentResultEntry, UtxoSpendInfo]>
  backup(destinationPath: string, password?: string | undefined | null): void
  static restoreWalletGuiApp(dataDir: string | undefined | null, walletFileName: string | undefined | null, rpcConfig: RpcConfig, backupFile: string, password?: string | undefined | null): void
  lockUnspendableUtxos(): void
  sendToAddress(address: string, amount: number, feeRate?: number | undefined | null, manuallySelectedOutpoints?: Array<OutPoint> | undefined | null): Txid
  /** Get wallet balances */
  getBalances(): Balances
  syncAndSave(): void
  displayOffer(makerOffer: Offer): string
  /** Recover from a failed swap */
  recoverFromSwap(): void
  fetchAllMakers(): Array<string>
  fetchOffers(): OfferBook
  static isWalletEncrypted(walletPath: string): boolean
}

export interface Address {
  address: string
}

export declare const enum AddressType {
  P2WPKH = 0,
  P2TR = 1
}

export interface Amount {
  sats: number
}

export interface Balances {
  regular: number
  swap: number
  contract: number
  fidelity: number
  spendable: number
}

export interface FeeRates {
  fastest: number
  standard: number
  economy: number
}

export interface FidelityBond {
  outpoint: OutPoint
  amount: Amount
  lockTime: LockTime
  pubkey: PublicKey
  confHeight?: number
  certExpiry?: number
  isSpent: boolean
}

export interface FidelityProof {
  bond: FidelityBond
  certHash: Array<number>
  certSig: Array<number>
}

export interface GetTransactionResultDetail {
  address?: Address
  category: string
  amount: SignedAmountSats
  label?: string
  vout: number
  fee?: SignedAmountSats
  abandoned?: boolean
}

export interface ListTransactionResult {
  info: WalletTxInfo
  detail: GetTransactionResultDetail
  trusted?: boolean
  comment?: string
}

export interface ListUnspentResultEntry {
  txid: Txid
  vout: number
  address?: string
  label?: string
  scriptPubKey: ScriptBuf
  amount: Amount
  confirmations: number
  redeemScript?: ScriptBuf
  witnessScript?: ScriptBuf
  spendable: boolean
  solvable: boolean
  desc?: string
  safe: boolean
}

export interface LockTime {
  lockType: string
  value: number
}

export interface MakerAddress {
  address: string
}

export interface MakerFeeInfo {
  makerIndex: number
  makerAddress: string
  baseFee: number
  amountRelativeFee: number
  timeRelativeFee: number
  totalFee: number
}

export interface MakerOfferCandidate {
  address: MakerAddress
  offer?: Offer
  state: MakerState
  protocol?: MakerProtocol
}

export interface MakerProtocol {
  /** Protocol type: "Legacy" or "Taproot" */
  protocolType: string
}

export interface MakerState {
  /** State type: "Good", "Unresponsive", or "Bad" */
  stateType: string
  /** Number of retries (only for Unresponsive state) */
  retries?: number
}

export interface Offer {
  baseFee: number
  amountRelativeFeePct: number
  timeRelativeFeePct: number
  requiredConfirms: number
  minimumLocktime: number
  maxSize: number
  minSize: number
  tweakablePoint: PublicKey
  fidelity: FidelityProof
}

export interface OfferBook {
  makers: Array<MakerOfferCandidate>
}

export interface OutPoint {
  txid: string
  vout: number
}

export interface PublicKey {
  compressed: boolean
  inner: Array<number>
}

export interface RpcConfig {
  url: string
  username: string
  password: string
  walletName: string
}

export interface ScriptBuf {
  hex: string
}

export interface SignedAmountSats {
  sats: number
}

export interface SwapParams {
  sendAmount: number
  makerCount: number
  manuallySelectedOutpoints?: Array<OutPoint>
}

export interface SwapReport {
  /** Unique swap ID */
  swapId: string
  /** Duration of the swap in seconds */
  swapDurationSeconds: number
  /** Target amount for the swap */
  targetAmount: number
  /** Total input amount */
  totalInputAmount: number
  /** Total output amount */
  totalOutputAmount: number
  /** Number of makers involved */
  makersCount: number
  /** List of maker addresses used */
  makerAddresses: Array<string>
  /** Total number of funding transactions */
  totalFundingTxs: number
  /** Funding transaction IDs organized by hop */
  fundingTxidsByHop: Array<Array<string>>
  /** Total fees paid */
  totalFee: number
  /** Total maker fees */
  totalMakerFees: number
  /** Mining fees */
  miningFee: number
  /** Fee percentage relative to target amount */
  feePercentage: number
  /** Individual maker fee information */
  makerFeeInfo: Array<MakerFeeInfo>
  /** Input UTXOs amounts */
  inputUtxos: Array<number>
  /** Output change UTXOs amounts */
  outputChangeAmounts: Array<number>
  /** Output swap coin UTXOs amounts */
  outputSwapAmounts: Array<number>
  /** Output change coin UTXOs with amounts and addresses [(amount, address)] */
  outputChangeUtxos: Array<UtxoWithAddress>
  /** Output swap coin UTXOs with amounts and addresses [(amount, address)] */
  outputSwapUtxos: Array<UtxoWithAddress>
}

export declare const enum TakerBehavior {
  Normal = 0,
  DropConnectionAfterFullSetup = 1,
  BroadcastContractAfterFullSetup = 2
}

export declare const enum TakerError {
  Wallet = 0,
  Protocol = 1,
  Network = 2,
  General = 3,
  IO = 4
}

/**
 * Swap parameters for Taproot (V2) protocol
 * Note: V2 has additional parameters compared to V1
 */
export interface TaprootSwapParams {
  /** Amount to send in satoshis */
  sendAmount: number
  /** Number of makers to use in the swap */
  makerCount: number
  /** Number of transaction splits (V2 specific) */
  txCount?: number
  /** Required confirmations for funding transactions (V2 specific) */
  requiredConfirms?: number
  /** User selected UTXOs (optional, for manual UTXO selection) */
  manuallySelectedOutpoints?: Array<OutPoint>
}

export interface Txid {
  value: string
}

export interface UtxoSpendInfo {
  spendType: string
  path?: string
  multisigRedeemscript?: ScriptBuf
  inputValue?: Amount
  index?: number
}

export interface UtxoWithAddress {
  amount: number
  address: string
}

export interface WalletBackup {
  fileName: string
}

export interface WalletTxInfo {
  confirmations: number
  blockhash?: string
  blockindex?: number
  blocktime?: number
  blockheight?: number
  txid: Txid
  time: number
  timereceived: number
  bip125Replaceable: string
  walletConflicts: Array<Txid>
}
