// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('fs')
const {
  isMusl: detectMusl,
  requireOptionalBinding,
  tryLoadNativeLibraryPathOverride,
} = require('./loader-security')
const isMusl = () => detectMusl(readFileSync)

let nativeBinding = null
const loadErrors = []

function requireNative() {
  try {
    const overrideBinding = tryLoadNativeLibraryPathOverride(__dirname)
    if (overrideBinding) {
      return overrideBinding
    }
  } catch (err) {
    loadErrors.push(err)
  }

  if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./coinswap-napi.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-android-arm64', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./coinswap-napi.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-android-arm-eabi', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
        return require('./coinswap-napi.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-win32-x64-gnu', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./coinswap-napi.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-win32-x64-msvc', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./coinswap-napi.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-win32-ia32-msvc', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./coinswap-napi.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-win32-arm64-msvc', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./coinswap-napi.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      return requireOptionalBinding('coinswap-napi-darwin-universal', __dirname)
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./coinswap-napi.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-darwin-x64', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./coinswap-napi.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-darwin-arm64', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./coinswap-napi.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-freebsd-x64', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./coinswap-napi.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-freebsd-arm64', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./coinswap-napi.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return requireOptionalBinding('coinswap-napi-linux-x64-musl', __dirname)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./coinswap-napi.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return requireOptionalBinding('coinswap-napi-linux-x64-gnu', __dirname)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./coinswap-napi.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return requireOptionalBinding('coinswap-napi-linux-arm64-musl', __dirname)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./coinswap-napi.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return requireOptionalBinding('coinswap-napi-linux-arm64-gnu', __dirname)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./coinswap-napi.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return requireOptionalBinding('coinswap-napi-linux-arm-musleabihf', __dirname)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./coinswap-napi.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return requireOptionalBinding('coinswap-napi-linux-arm-gnueabihf', __dirname)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./coinswap-napi.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return requireOptionalBinding('coinswap-napi-linux-loong64-musl', __dirname)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./coinswap-napi.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return requireOptionalBinding('coinswap-napi-linux-loong64-gnu', __dirname)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./coinswap-napi.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return requireOptionalBinding('coinswap-napi-linux-riscv64-musl', __dirname)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./coinswap-napi.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          return requireOptionalBinding('coinswap-napi-linux-riscv64-gnu', __dirname)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./coinswap-napi.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-linux-ppc64-gnu', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./coinswap-napi.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-linux-s390x-gnu', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./coinswap-napi.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-openharmony-arm64', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./coinswap-napi.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-openharmony-x64', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./coinswap-napi.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return requireOptionalBinding('coinswap-napi-openharmony-arm', __dirname)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → force WASI fallback even if native loaded
//   'error'                  → force WASI and throw if no WASI binding is found
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' || process.env.NAPI_RS_FORCE_WASI === 'error'

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./coinswap-napi.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (forceWasi) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || forceWasi) {
    try {
      wasiBinding = requireOptionalBinding('coinswap-napi-wasm32-wasi', __dirname)
      nativeBinding = wasiBinding
    } catch (err) {
      if (forceWasi) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = loadErrors.reduce((err, cur) => {
      cur.cause = err
      return cur
    })
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.Taker = nativeBinding.Taker
module.exports.AddressType = nativeBinding.AddressType
module.exports.TakerBehavior = nativeBinding.TakerBehavior
module.exports.TakerError = nativeBinding.TakerError
