/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Taker {
  constructor(dataDir?: string | undefined | null, walletFileName?: string | undefined | null, rpcConfig?: RpcConfig | undefined | null, behavior?: TakerBehavior | undefined | null, controlPort?: number | undefined | null, torAuthPassword?: string | undefined | null)
  doCoinswap(swapParams: SwapParams): SwapReport | null
  getWalletName(): string
  /** Get wallet balances */
  getWalletBalances(): Balances
  syncWallet(): void
  /** Sync the offerbook with available makers */
  syncOfferbook(): void
  /** Get basic information about all good makers (limited due to private fields) */
  getAllGoodMakers(): Array<string>
  displayOffer(makerOffer: Offer): string
  /** Recover from a failed swap */
  recoverFromSwap(): void
  fetchGoodMakers(): Array<string>
  fetchAllMakers(): Array<string>
  fetchOffers(): OfferBook
}

export declare class Wallet {
  constructor(path: string, rpcConfig: RpcConfig)
  getBalances(): Balances
  getTransactions(count?: number | undefined | null, skip?: number | undefined | null): Array<ListTransactionResult>
  getNextInternalAddresses(count: number): Array<Address>
  getNextExternalAddress(): Address
  getName(): string
  listAllUtxos(): Array<[ListUnspentResultEntry, UtxoSpendInfo]>
  syncAndSave(): void
  backup(path: string): void
  lockUnspendableUtxos(): void
  sendToAddress(address: string, amount: number): Txid
}

export interface Address {
  address: string
}

export interface Amount {
  sats: number
}

export interface Balances {
  regular: number
  swap: number
  contract: number
  fidelity: number
  spendable: number
}

export declare function createDefaultRpcConfig(): RpcConfig

export declare function createSwapParams(sendAmount: number, makerCount: number, outpoints: Array<OutPoint>): SwapParams

export interface FidelityBond {
  outpoint: OutPoint
  amount: Amount
  lockTime: LockTime
  pubkey: PublicKey
  confHeight?: number
  certExpiry?: number
  isSpent: boolean
}

export interface FidelityProof {
  bond: FidelityBond
  certHash: string
  certSig: number
}

export interface GetTransactionResultDetail {
  address?: Address
  category: string
  amount: SignedAmountSats
  label?: string
  vout: number
  fee?: SignedAmountSats
  abandoned?: boolean
}

export interface ListTransactionResult {
  info: WalletTxInfo
  detail: GetTransactionResultDetail
  trusted?: boolean
  comment?: string
}

export interface ListUnspentResultEntry {
  txid: Txid
  vout: number
  address?: string
  label?: string
  scriptPubKey: ScriptBuf
  amount: Amount
  confirmations: number
  redeemScript?: ScriptBuf
  witnessScript?: ScriptBuf
  spendable: boolean
  solvable: boolean
  desc?: string
  safe: boolean
}

export interface LockTime {
  lockType: string
  value: number
}

export interface MakerAddress {
  address: string
}

export interface MakerFeeInfo {
  makerIndex: number
  makerAddress: string
  baseFee: number
  amountRelativeFee: number
  timeRelativeFee: number
  totalFee: number
}

export interface Offer {
  baseFee: number
  amountRelativeFeePct: number
  timeRelativeFeePct: number
  requiredConfirms: number
  minimumLocktime: number
  maxSize: number
  minSize: number
  tweakablePoint: PublicKey
  fidelity: FidelityProof
}

export interface OfferAndAddress {
  offer: Offer
  address: MakerAddress
  timestamp: string
}

export interface OfferBook {
  goodMakers: Array<OfferAndAddress>
  allMakers: Array<OfferAndAddress>
}

export interface OutPoint {
  txid: string
  vout: number
}

export interface PublicKey {
  compressed: boolean
  inner: Array<number>
}

export interface RpcConfig {
  url: string
  username: string
  password: string
  walletName: string
}

export interface ScriptBuf {
  hex: string
}

export interface SignedAmountSats {
  sats: number
}

export interface SwapParams {
  sendAmount: number
  makerCount: number
  manuallySelectedOutpoints?: Array<OutPoint>
}

export interface SwapReport {
  /** Unique swap ID */
  swapId: string
  /** Duration of the swap in seconds */
  swapDurationSeconds: number
  /** Target amount for the swap */
  targetAmount: number
  /** Total input amount */
  totalInputAmount: number
  /** Total output amount */
  totalOutputAmount: number
  /** Number of makers involved */
  makersCount: number
  /** List of maker addresses used */
  makerAddresses: Array<string>
  /** Total number of funding transactions */
  totalFundingTxs: number
  /** Funding transaction IDs organized by hop */
  fundingTxidsByHop: Array<Array<string>>
  /** Total fees paid */
  totalFee: number
  /** Total maker fees */
  totalMakerFees: number
  /** Mining fees */
  miningFee: number
  /** Fee percentage relative to target amount */
  feePercentage: number
  /** Individual maker fee information */
  makerFeeInfo: Array<MakerFeeInfo>
  /** Input UTXOs amounts */
  inputUtxos: Array<number>
  /** Output regular UTXOs amounts */
  outputRegularUtxos: Array<number>
  /** Output swap coin UTXOs amounts */
  outputSwapUtxos: Array<number>
}

export declare const enum TakerBehavior {
  Normal = 0,
  DropConnectionAfterFullSetup = 1,
  BroadcastContractAfterFullSetup = 2
}

export declare const enum TakerError {
  Wallet = 0,
  Protocol = 1,
  Network = 2,
  General = 3,
  IO = 4
}

export interface Txid {
  hex: string
}

export interface UtxoSpendInfo {
  spendType: string
  path?: string
  multisigRedeemscript?: ScriptBuf
  inputValue?: Amount
  index?: number
  originalMultisigRedeemscript?: ScriptBuf
}

export interface WalletBackup {
  fileName: string
}

export declare const enum WalletError {
  IO = 0,
  Rpc = 1,
  General = 2,
  Json = 3,
  Network = 4,
  AddressParse = 5
}

export interface WalletTxInfo {
  confirmations: number
  blockhash?: string
  blockindex?: number
  blocktime?: number
  blockheight?: number
  txid: Txid
  time: number
  timereceived: number
  bip125Replaceable: string
  walletConflicts: Array<Txid>
}
