/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Taker {
  constructor(dataDir?: string | undefined | null, walletFileName?: string | undefined | null, rpcConfig?: RpcConfig | undefined | null, behavior?: TakerBehavior | undefined | null, controlPort?: number | undefined | null, torAuthPassword?: string | undefined | null)
  sendCoinswap(swapParams: SwapParams): void
  getWalletName(): string
  /** Get wallet balances */
  getWalletBalances(): Balances
  syncWallet(): void
  /** Sync the offerbook with available makers */
  syncOfferbook(): void
  /** Get basic information about all good makers (limited due to private fields) */
  getAllGoodMakers(): Array<string>
  /** Display detailed information about a specific maker offer */
  displayOffer(makerOffer: MakerOffer): string
  /** Recover from a failed swap */
  recoverFromSwap(): void
  fetchGoodMakers(): Array<string>
  fetchAllMakers(): Array<string>
}

export declare class Wallet {
  constructor(path: string, rpcConfig: RpcConfig)
  getBalances(): Balances
  getNextInternalAddresses(count: number): Array<Address>
  getNextExternalAddress(): Address
  /** Get the wallet name */
  getName(): string
  listAllUtxos(): Array<UtxoWithSpendInfo>
  syncAndSave(): void
  backup(path: string): void
  lockUnspendableUtxos(): void
}

export interface Address {
  address: string
}

export interface Amount {
  sats: number
}

export interface Balances {
  regular: number
  swap: number
  contract: number
  fidelity: number
  spendable: number
}

export declare function createDefaultRpcConfig(): RpcConfig

export declare function createSwapParams(sendAmount: number, makerCount: number, outpoints: Array<OutPoint>): SwapParams

export interface ListUnspentResultEntry {
  txid: Txid
  vout: number
  address?: string
  label?: string
  scriptPubKey: ScriptBuf
  amount: Amount
  confirmations: number
  redeemScript?: ScriptBuf
  witnessScript?: ScriptBuf
  spendable: boolean
  solvable: boolean
  desc?: string
  safe: boolean
}

export interface MakerOffer {
  baseFee: number
  amountRelativeFeePct: number
  timeRelativeFeePct: number
  requiredConfirms: number
  minimumLocktime: number
  maxSize: number
  minSize: number
  address: string
}

export interface MakerStats {
  totalMakers: number
  onlineMakers: number
  avgBaseFee: number
  avgAmountRelativeFeePct: number
  avgTimeRelativeFeePct: number
  totalLiquidity: number
  avgMinSize: number
  avgMaxSize: number
}

export interface OutPoint {
  txid: string
  vout: number
}

export interface RpcConfig {
  url: string
  username: string
  password: string
  walletName: string
}

export interface ScriptBuf {
  hex: string
}

export interface SwapParams {
  /** Total Amount */
  sendAmount: number
  /** How many hops (number of makers) */
  makerCount: number
  /** User selected UTXOs (optional) */
  manuallySelectedOutpoints?: Array<OutPoint>
}

export declare const enum TakerBehavior {
  Normal = 0,
  DropConnectionAfterFullSetup = 1,
  BroadcastContractAfterFullSetup = 2
}

export declare const enum TakerError {
  Wallet = 0,
  Protocol = 1,
  Network = 2,
  General = 3,
  IO = 4
}

export interface Txid {
  hex: string
}

export interface UtxoSpendInfo {
  spendType: string
  path?: string
  multisigRedeemscript?: ScriptBuf
  inputValue?: Amount
  index?: number
  originalMultisigRedeemscript?: ScriptBuf
}

export interface UtxoWithSpendInfo {
  utxo: ListUnspentResultEntry
  spendInfo: UtxoSpendInfo
}

export interface WalletBackup {
  fileName: string
}

export declare const enum WalletError {
  IO = 0,
  RPC = 1,
  General = 2,
  JSON = 3,
  Network = 4,
  AddressParse = 5
}
