plugins {
    kotlin("jvm") version "1.9.22"
}

group = "tech.citadel.coinswap"
version = "0.1.0"

repositories {
    mavenCentral()
}

dependencies {
    // Kotlin standard library
    implementation(kotlin("stdlib"))
    
    // JUnit for testing
    testImplementation("junit:junit:4.13.2")
    
    // JNA - required by UniFFI for native library loading
    testImplementation("net.java.dev.jna:jna:5.13.0")
    
    // Coinswap FFI bindings (generated by UniFFI)
    // This should point to the generated JAR file after running UniFFI bindgen
    testImplementation(files("../../target/debug/libcoinswap_ffi.jar"))
    
    // Alternative: if you build the JAR separately
    // testImplementation(files("../../../coinswap-ffi.jar"))
}

tasks.test {
    useJUnit()
    
    // Show test output
    testLogging {
        events("passed", "skipped", "failed", "standardOut", "standardError")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showExceptions = true
        showCauses = true
        showStackTraces = true
    }
    
    // Run tests sequentially (important for bitcoind tests)
    maxParallelForks = 1
    
    // Increase test timeout
    systemProperty("junit.jupiter.execution.timeout.default", "5m")
}

// Kotlin compiler options
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "11"
        freeCompilerArgs = listOf("-Xjsr305=strict")
    }
}

// Source sets configuration
sourceSets {
    test {
        kotlin {
            srcDirs(".")
        }
    }
}
